apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: ankit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mew
      tier: cat
  template:
    metadata:
      labels:
        app: mew
        tier: cat
    spec:
      containers:
        - name: ankitmew
          image: ankitmaji209/kube-first-app
          imagePullPolicy: Always
